-- directory.sql


/* =============================================
 * CREATE TABLE core."directory"
 * ============================================*/
create table core."directory" (
	directory_id int generated by default as identity,
	constraint directory_pk primary key (directory_id)
);
comment on table core."directory" is '';	


-- =============================================
-- FIELD: directory_name text
-- =============================================
-- ADD directory_name
alter table core."directory" add directory_name text  ;
comment on column core."directory".directory_name is '';

-- MODIFY directory_name
alter table core."directory"
	alter column directory_name type text,
	ALTER COLUMN directory_name DROP DEFAULT,
	ALTER COLUMN directory_name DROP NOT NULL;
comment on column core."directory".directory_name is '';


-- =============================================
-- FIELD: directory_descr text
-- =============================================
-- ADD directory_descr
alter table core."directory" add directory_descr text  ;
comment on column core."directory".directory_descr is '';

-- MODIFY directory_descr
alter table core."directory"
	alter column directory_descr type text,
	ALTER COLUMN directory_descr DROP DEFAULT,
	ALTER COLUMN directory_descr DROP NOT NULL;
comment on column core."directory".directory_descr is '';


-- =============================================
-- FIELD: directory_icon text
-- =============================================
-- ADD directory_icon
alter table core."directory" add directory_icon text  ;
comment on column core."directory".directory_icon is '';

-- MODIFY directory_icon
alter table core."directory"
	alter column directory_icon type text,
	ALTER COLUMN directory_icon DROP DEFAULT,
	ALTER COLUMN directory_icon DROP NOT NULL;
comment on column core."directory".directory_icon is '';


-- =============================================
-- FIELD: directory_parent int
-- =============================================
-- ADD directory_parent
alter table core."directory" add directory_parent int  ;
comment on column core."directory".directory_parent is '';

-- MODIFY directory_parent
alter table core."directory"
	alter column directory_parent type int,
	ALTER COLUMN directory_parent DROP DEFAULT,
	ALTER COLUMN directory_parent DROP NOT NULL;
comment on column core."directory".directory_parent is '';


-- =============================================
-- FIELD: directory_path text
-- =============================================
-- ADD directory_path
alter table core."directory" add directory_path text  ;
comment on column core."directory".directory_path is '';

-- MODIFY directory_path
alter table core."directory"
	alter column directory_path type text,
	ALTER COLUMN directory_path DROP DEFAULT,
	ALTER COLUMN directory_path DROP NOT NULL;
comment on column core."directory".directory_path is '';


-- =============================================
-- FIELD: directory_pathid text
-- =============================================
-- ADD directory_pathid
alter table core."directory" add directory_pathid text  ;
comment on column core."directory".directory_pathid is '';

-- MODIFY directory_pathid
alter table core."directory"
	alter column directory_pathid type text,
	ALTER COLUMN directory_pathid DROP DEFAULT,
	ALTER COLUMN directory_pathid DROP NOT NULL;
comment on column core."directory".directory_pathid is '';


-- =============================================
-- FIELD: directory_level int
-- =============================================
-- ADD directory_level
alter table core."directory" add directory_level int not null default 0;
comment on column core."directory".directory_level is '';

-- MODIFY directory_level
alter table core."directory"
	alter column directory_level type int,
	ALTER COLUMN directory_level SET DEFAULT 0,
	ALTER COLUMN directory_level SET NOT NULL;
comment on column core."directory".directory_level is '';


-- =============================================
-- FIELD: _createby bigint
-- =============================================
-- ADD _createby
alter table core."directory" add _createby bigint not null ;
comment on column core."directory"._createby is 'user yang pertama kali membuat record ini';

-- MODIFY _createby
alter table core."directory"
	alter column _createby type bigint,
	ALTER COLUMN _createby DROP DEFAULT,
	ALTER COLUMN _createby SET NOT NULL;
comment on column core."directory"._createby is 'user yang pertama kali membuat record ini';


-- =============================================
-- FIELD: _createdate timestamp with time zone
-- =============================================
-- ADD _createdate
alter table core."directory" add _createdate timestamp with time zone not null ;
comment on column core."directory"._createdate is 'waktu record dibuat pertama kali';

-- MODIFY _createdate
alter table core."directory"
	alter column _createdate type timestamp with time zone,
	ALTER COLUMN _createdate DROP DEFAULT,
	ALTER COLUMN _createdate SET NOT NULL;
comment on column core."directory"._createdate is 'waktu record dibuat pertama kali';


-- =============================================
-- FIELD: _modifyby bigint
-- =============================================
-- ADD _modifyby
alter table core."directory" add _modifyby bigint  ;
comment on column core."directory"._modifyby is 'user yang terakhir modifikasi record ini';

-- MODIFY _modifyby
alter table core."directory"
	alter column _modifyby type bigint,
	ALTER COLUMN _modifyby DROP DEFAULT,
	ALTER COLUMN _modifyby DROP NOT NULL;
comment on column core."directory"._modifyby is 'user yang terakhir modifikasi record ini';


-- =============================================
-- FIELD: _modifydate timestamp with time zone
-- =============================================
-- ADD _modifydate
alter table core."directory" add _modifydate timestamp with time zone  ;
comment on column core."directory"._modifydate is 'waktu terakhir record dimodifikasi';

-- MODIFY _modifydate
alter table core."directory"
	alter column _modifydate type timestamp with time zone,
	ALTER COLUMN _modifydate DROP DEFAULT,
	ALTER COLUMN _modifydate DROP NOT NULL;
comment on column core."directory"._modifydate is 'waktu terakhir record dimodifikasi';




-- =============================================
-- FOREIGN KEY CONSTRAINT
-- =============================================
-- Drop Existing Foreign Key Constraint 
ALTER TABLE core."directory" DROP CONSTRAINT fk$core$directory$directory_parent;


-- Add Foreign Key Constraint  
ALTER TABLE core."directory"
	ADD CONSTRAINT fk$core$directory$directory_parent
	FOREIGN KEY (directory_parent)
	REFERENCES core."directory"(directory_id);
	


-- =============================================
-- UNIQUE INDEX
-- =============================================
-- Drop existing unique index 
alter table core."directory"
	drop constraint uq$core$directory$directory_name;
	

-- Add unique index 
alter table  core."directory"
	add constraint uq$core$directory$directory_name unique (directory_name); 

