CREATE TABLE core.sequencer_doc (
	sequencer_id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	sequencer_year int4 DEFAULT 0 NOT NULL,
	sequencer_month int4 DEFAULT 0 NOT NULL,
	sequencer_seqnum int4 DEFAULT 0 NOT NULL,
	sequencer_block int4 DEFAULT 0 NOT NULL,
	sequencer_cluster int4 DEFAULT 0 NOT NULL,
	sequencer_number int4 DEFAULT 0 NOT NULL,
	sequencer_lastdate date DEFAULT now() NULL,
	sequencer_remark text NULL,
	"_createby" int8 NOT NULL,
	"_createdate" timestamptz NOT NULL,
	"_modifyby" int8 NULL,
	"_modifydate" timestamptz NULL,
	CONSTRAINT sequencer_pk PRIMARY KEY (sequencer_id),
	CONSTRAINT "uq$core$sequencer$sequencer_line" UNIQUE (sequencer_year, sequencer_month, sequencer_seqnum, sequencer_block, sequencer_cluster)
);