-- sequencer.sql


/* =============================================
 * CREATE TABLE core."sequencer"
 * ============================================*/
create table core."sequencer" (
	sequencer_id int generated by default as identity,
	constraint sequencer_pk primary key (sequencer_id)
);
comment on table core."sequencer" is 'sequencer document';	


-- =============================================
-- FIELD: sequencer_year int
-- =============================================
-- ADD sequencer_year
alter table core."sequencer" add sequencer_year int not null default 0;
comment on column core."sequencer".sequencer_year is '';

-- MODIFY sequencer_year
alter table core."sequencer"
	alter column sequencer_year type int,
	ALTER COLUMN sequencer_year SET DEFAULT 0,
	ALTER COLUMN sequencer_year SET NOT NULL;
comment on column core."sequencer".sequencer_year is '';


-- =============================================
-- FIELD: sequencer_month int
-- =============================================
-- ADD sequencer_month
alter table core."sequencer" add sequencer_month int not null default 0;
comment on column core."sequencer".sequencer_month is '';

-- MODIFY sequencer_month
alter table core."sequencer"
	alter column sequencer_month type int,
	ALTER COLUMN sequencer_month SET DEFAULT 0,
	ALTER COLUMN sequencer_month SET NOT NULL;
comment on column core."sequencer".sequencer_month is '';


-- =============================================
-- FIELD: sequencer_seqnum int
-- =============================================
-- ADD sequencer_seqnum
alter table core."sequencer" add sequencer_seqnum int not null default 0;
comment on column core."sequencer".sequencer_seqnum is '';

-- MODIFY sequencer_seqnum
alter table core."sequencer"
	alter column sequencer_seqnum type int,
	ALTER COLUMN sequencer_seqnum SET DEFAULT 0,
	ALTER COLUMN sequencer_seqnum SET NOT NULL;
comment on column core."sequencer".sequencer_seqnum is '';


-- =============================================
-- FIELD: sequencer_block int
-- =============================================
-- ADD sequencer_block
alter table core."sequencer" add sequencer_block int not null default 0;
comment on column core."sequencer".sequencer_block is '';

-- MODIFY sequencer_block
alter table core."sequencer"
	alter column sequencer_block type int,
	ALTER COLUMN sequencer_block SET DEFAULT 0,
	ALTER COLUMN sequencer_block SET NOT NULL;
comment on column core."sequencer".sequencer_block is '';


-- =============================================
-- FIELD: sequencer_cluster int
-- =============================================
-- ADD sequencer_cluster
alter table core."sequencer" add sequencer_cluster int not null default 0;
comment on column core."sequencer".sequencer_cluster is '';

-- MODIFY sequencer_cluster
alter table core."sequencer"
	alter column sequencer_cluster type int,
	ALTER COLUMN sequencer_cluster SET DEFAULT 0,
	ALTER COLUMN sequencer_cluster SET NOT NULL;
comment on column core."sequencer".sequencer_cluster is '';


-- =============================================
-- FIELD: sequencer_number int
-- =============================================
-- ADD sequencer_number
alter table core."sequencer" add sequencer_number int not null default 0;
comment on column core."sequencer".sequencer_number is '';

-- MODIFY sequencer_number
alter table core."sequencer"
	alter column sequencer_number type int,
	ALTER COLUMN sequencer_number SET DEFAULT 0,
	ALTER COLUMN sequencer_number SET NOT NULL;
comment on column core."sequencer".sequencer_number is '';


-- =============================================
-- FIELD: sequencer_lastdate date
-- =============================================
-- ADD sequencer_lastdate
alter table core."sequencer" add sequencer_lastdate date  default now();
comment on column core."sequencer".sequencer_lastdate is '';

-- MODIFY sequencer_lastdate
alter table core."sequencer"
	alter column sequencer_lastdate type date,
	ALTER COLUMN sequencer_lastdate SET DEFAULT now(),
	ALTER COLUMN sequencer_lastdate DROP NOT NULL;
comment on column core."sequencer".sequencer_lastdate is '';


-- =============================================
-- FIELD: sequencer_remark text
-- =============================================
-- ADD sequencer_remark
alter table core."sequencer" add sequencer_remark text  ;
comment on column core."sequencer".sequencer_remark is '';

-- MODIFY sequencer_remark
alter table core."sequencer"
	alter column sequencer_remark type text,
	ALTER COLUMN sequencer_remark DROP DEFAULT,
	ALTER COLUMN sequencer_remark DROP NOT NULL;
comment on column core."sequencer".sequencer_remark is '';


-- =============================================
-- FIELD: _createby bigint
-- =============================================
-- ADD _createby
alter table core."sequencer" add _createby bigint not null ;
comment on column core."sequencer"._createby is 'user yang pertama kali membuat record ini';

-- MODIFY _createby
alter table core."sequencer"
	alter column _createby type bigint,
	ALTER COLUMN _createby DROP DEFAULT,
	ALTER COLUMN _createby SET NOT NULL;
comment on column core."sequencer"._createby is 'user yang pertama kali membuat record ini';


-- =============================================
-- FIELD: _createdate timestamp with time zone
-- =============================================
-- ADD _createdate
alter table core."sequencer" add _createdate timestamp with time zone not null ;
comment on column core."sequencer"._createdate is 'waktu record dibuat pertama kali';

-- MODIFY _createdate
alter table core."sequencer"
	alter column _createdate type timestamp with time zone,
	ALTER COLUMN _createdate DROP DEFAULT,
	ALTER COLUMN _createdate SET NOT NULL;
comment on column core."sequencer"._createdate is 'waktu record dibuat pertama kali';


-- =============================================
-- FIELD: _modifyby bigint
-- =============================================
-- ADD _modifyby
alter table core."sequencer" add _modifyby bigint  ;
comment on column core."sequencer"._modifyby is 'user yang terakhir modifikasi record ini';

-- MODIFY _modifyby
alter table core."sequencer"
	alter column _modifyby type bigint,
	ALTER COLUMN _modifyby DROP DEFAULT,
	ALTER COLUMN _modifyby DROP NOT NULL;
comment on column core."sequencer"._modifyby is 'user yang terakhir modifikasi record ini';


-- =============================================
-- FIELD: _modifydate timestamp with time zone
-- =============================================
-- ADD _modifydate
alter table core."sequencer" add _modifydate timestamp with time zone  ;
comment on column core."sequencer"._modifydate is 'waktu terakhir record dimodifikasi';

-- MODIFY _modifydate
alter table core."sequencer"
	alter column _modifydate type timestamp with time zone,
	ALTER COLUMN _modifydate DROP DEFAULT,
	ALTER COLUMN _modifydate DROP NOT NULL;
comment on column core."sequencer"._modifydate is 'waktu terakhir record dimodifikasi';




-- =============================================
-- FOREIGN KEY CONSTRAINT
-- =============================================
-- Add Foreign Key Constraint  	


-- =============================================
-- UNIQUE INDEX
-- =============================================
-- Add unique index 
alter table  core."sequencer"
	add constraint uq$core$sequencer$sequencer_line unique (sequencer_year, sequencer_month, sequencer_seqnum, sequencer_block, sequencer_cluster); 

